### ISSUE TITLE
readme提到的问题解决了吗？

### ISSUE THREAD

**Issue by WAI-f** [dadwadw233/Central_Voting_PPF#7]
我看这个仓库还在不断更新，想了解目前您warning中提到的问题解决了吗

**Comment by dadwadw233** [comment]
感谢关注，如果您关心的是warning中提及的第一条内容：“无法复现论文中实验结果”，该问题目前没有解决。该repo在近期的更新仅修复了部分代码实现中的bug。在早期通过使用该代码进行测试时，虽然无法得到如论文中优秀的指标，但是通过一些方式我检验了central point voting与ppf的结合是可行的。关于一些代码实现细节与数据预处理的方式在论文中没有具体的阐述，这是我认为导致最终结果欠佳的主要原因。
